import { execSync, spawn } from 'child_process'
import { existsSync, readFileSync, writeFileSync, mkdirSync } from 'fs'
import { resolve } from 'path'
import * as readline from 'readline'

interface Requirement {
  name: string
  check: () => boolean | Promise<boolean>
  install?: () => void | Promise<void>
  optional?: boolean
  version?: string
}

export class Installer {
  private requirements: Requirement[] = []
  private missing: Requirement[] = []
  private errors: string[] = []

  addRequirement(req: Requirement) {
    this.requirements.push(req)
  }

  async checkAll() {
    this.missing = []
    this.errors = []
    for (const req of this.requirements) {
      try {
        const ok = await req.check()
        if (!ok) {
          this.missing.push(req)
          console.log(`  ✗ ${req.name}${req.optional ? ' (optional)' : ''}`)
        } else {
          console.log(`  ✓ ${req.name}`)
        }
      } catch (e: any) {
        this.errors.push(`${req.name}: ${e.message}`)
        if (!req.optional) this.missing.push(req)
        console.log(`  ✗ ${req.name} - error: ${e.message}`)
      }
    }
  }

  async installMissing() {
    if (!this.missing.length) {
      console.log('\n  ✔ All requirements satisfied!')
      return
    }

    console.log(`\n  ⚠ ${this.missing.length} requirement(s) missing. Attempting auto-install...\n`)

    for (const req of this.missing) {
      if (req.install) {
        try {
          console.log(`  Installing ${req.name}...`)
          await req.install()
          console.log(`  ✔ ${req.name} installed`)
        } catch (e: any) {
          console.error(`  ✗ Failed to install ${req.name}: ${e.message}`)
          this.errors.push(`${req.name}: install failed - ${e.message}`)
        }
      } else {
        console.log(`  ⚠ ${req.name} must be installed manually`)
        this.errors.push(`${req.name}: manual installation required`)
      }
    }
  }

  get hasErrors() { return this.errors.length > 0 }
  getErrors() { return this.errors }

  summary() {
    return {
      total: this.requirements.length,
      satisfied: this.requirements.length - this.missing.length,
      missing: this.missing.length,
      errors: this.errors.length,
    }
  }
}

export function checkCommand(cmd: string) {
  try {
    execSync(`which ${cmd} 2>/dev/null || command -v ${cmd} 2>/dev/null`, { stdio: 'ignore' })
    return true
  } catch { return false }
}

export function checkNodeVersion(min = '18.0.0') {
  try {
    const v = execSync('node --version').toString().trim().replace(/^v/, '')
    const parts = v.split('.').map(Number)
    const minParts = min.split('.').map(Number)
    for (let i = 0; i < 3; i++) {
      if ((parts[i] || 0) > (minParts[i] || 0)) return true
      if ((parts[i] || 0) < (minParts[i] || 0)) return false
    }
    return true
  } catch { return false }
}

export function detectPackageManager() {
  if (existsSync(resolve(process.cwd(), 'pnpm-lock.yaml'))) return 'pnpm'
  if (existsSync(resolve(process.cwd(), 'yarn.lock'))) return 'yarn'
  if (existsSync(resolve(process.cwd(), 'package-lock.json'))) return 'npm'
  return 'npm'
}

export async function createEnvFile() {
  const envPath = resolve(process.cwd(), '.env')
  if (existsSync(envPath)) {
    console.log('  .env already exists, skipping')
    return
  }
  const rl = readline.createInterface({ input: process.stdin, output: process.stdout })
  const ask = (q: string): Promise<string> => new Promise(r => rl.question(q, r))

  console.log('\n  ┌─ Cocokalo Setup ──────────────────────────────────┐')
  console.log('  │  Let us configure your environment                │')
  console.log('  └───────────────────────────────────────────────────┘\n')

  const dbUser = await ask('  Database user [postgres]: ') || 'postgres'
  const dbPass = await ask('  Database password [123]: ') || '123'
  const dbHost = await ask('  Database host [localhost]: ') || 'localhost'
  const dbPort = await ask('  Database port [5432]: ') || '5432'
  const dbName = await ask('  Database name [cocokalo]: ') || 'cocokalo'
  const redisUrl = await ask('  Redis URL [redis://localhost:6379]: ') || 'redis://localhost:6379'
  const jwtSecret = await ask('  JWT Secret (press enter for random): ') || require('crypto').randomBytes(32).toString('hex')
  const siteUrl = await ask('  Site URL [http://localhost:3000]: ') || 'http://localhost:3000'

  rl.close()

  const env = `# Cocokalo - Generated by setup wizard
DATABASE_URL="postgresql://${dbUser}:${dbPass}@${dbHost}:${dbPort}/${dbName}"
REDIS_URL="${redisUrl}"
PG_HOST="${dbHost}"
PG_PORT="${dbPort}"
PG_USER="${dbUser}"
PG_PASSWORD="${dbPass}"
PG_DB="${dbName}"
JWT_SECRET="${jwtSecret}"
SITE_URL="${siteUrl}"
NODE_ENV="development"
`

  writeFileSync(envPath, env, 'utf-8')
  console.log('\n  ✔ .env file created')
}

export async function installDependencies() {
  const pm = detectPackageManager()
  console.log(`  Using package manager: ${pm}`)
  try {
    execSync(`${pm} install`, { stdio: 'inherit', cwd: process.cwd() })
    console.log('  ✔ Dependencies installed')
  } catch (e: any) {
    throw new Error(`Failed to install dependencies: ${e.message}`)
  }
}

export async function runPrismaGenerate() {
  try {
    execSync('npx prisma generate', { stdio: 'inherit', cwd: process.cwd() })
    console.log('  ✔ Prisma client generated')
  } catch (e: any) {
    throw new Error(`Failed to generate Prisma client: ${e.message}`)
  }
}

export async function runDbMigrate() {
  try {
    execSync('npx prisma db push', { stdio: 'inherit', cwd: process.cwd() })
    console.log('  ✔ Database migrated')
  } catch (e: any) {
    throw new Error(`Failed to migrate database: ${e.message}`)
  }
}
