#!/usr/bin/env python3
"""Generate the two font headers hudos_server.c needs but the repo never
committed: userland/sun8x16.h (ASCII 8x16) and userland/cjk16x16.h (CJK 32x32).

ASCII : extracted from the system X11 fixed 8x16 PCF font (classic bitmap).
CJK   : rendered with ffmpeg drawtext + WenQuanYi Micro Hei, one frame per
        character, then box-downsampled into the 32x32 cell the kcon code
        expects (32 rows x 32 bits, MSB = leftmost pixel).

Usage: python3 gen_fonts.py [source_file ...]
       (defaults to ../hudos_server.c; every unique non-ASCII char found
        becomes one glyph)
"""
import os
import struct
import gzip
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
PCF = "/usr/share/fonts/X11/misc/8x16.pcf.gz"
CJK_FONT = "/usr/share/fonts/truetype/wqy/wqy-microhei.ttc"

# kcon_draw_cell(): 32 rows per glyph, one 32-bit word per row, 0x80000000 >> x
CELL = 32
# render size for CJK: em box = FS px inside a canvas that cannot clip it
FS = 64
CANVAS = 128
PEN = 32  # fixed pen origin for every glyph (consistent baseline & advance)

# ---------------------------------------------------------------- ASCII ----

def load_pcf(path):
    """-> dict char -> 16 rows of 8 bits (MSB = left pixel)."""
    d = gzip.open(path, "rb").read()
    magic, n = struct.unpack("<II", d[:8])
    if magic != 0x70636601:
        raise SystemExit("not a PCF file")
    T = {}
    for i in range(n):
        t, f, s, o = struct.unpack("<IIII", d[8 + i * 16:24 + i * 16])
        T[t] = (f, s, o)

    # encoding table: char code -> glyph index (single-byte plane)
    _, _, o = T[32]
    mc0, mc1, mb0, mb1, _df = struct.unpack(">5h", d[o + 4:o + 14])
    cnt = (mc1 - mc0 + 1) * (mb1 - mb0 + 1)
    idx = struct.unpack(">%dh" % cnt, d[o + 14:o + 14 + 2 * cnt])
    char2g = {}
    i = 0
    for b in range(mb0, mb1 + 1):
        for c in range(mc0, mc1 + 1):
            g = idx[i]
            i += 1
            if g >= 0 and b == 0:
                char2g[c] = g

    # bitmap table
    _, _, o = T[8]
    fmt, = struct.unpack("<I", d[o:o + 4])
    gc, = struct.unpack(">I", d[o + 4:o + 8])
    offs = struct.unpack(">%dI" % gc, d[o + 8:o + 8 + 4 * gc])
    sizes = struct.unpack(">4I", d[o + 8 + 4 * gc:o + 8 + 4 * gc + 16])
    data = d[o + 8 + 4 * gc + 16:o + 8 + 4 * gc + 16 + sum(sizes)]

    out = {}
    for ch, g in char2g.items():
        start = offs[g]
        end = offs[g + 1] if g + 1 < gc else len(data)
        blob = data[start:end]
        stride = len(blob) // 16
        rows = []
        for r in range(16):
            row = blob[r * stride:(r + 1) * stride]
            bits = 0
            for b in range(8):
                if row[0] & (0x80 >> b):
                    bits |= 0x80 >> b
            rows.append(bits)
        out[ch] = rows
    return out

def emit_sun8x16(font, path):
    lines = [
        "/* SUN8x16 - ASCII 8x16 bitmap font, 256 chars x 16 rows.",
        " * Auto-generated by gen_fonts.py from %s. */" % PCF,
        "#ifndef HUDOS_SUN8X16_H",
        "#define HUDOS_SUN8X16_H",
        "",
        "static const unsigned char SUN8x16[256 * 16] = {",
    ]
    for ch in range(256):
        rows = font.get(ch, [0] * 16)
        body = ",".join("0x%02X" % r for r in rows)
        name = chr(ch) if 32 <= ch < 127 else "0x%02X" % ch
        lines.append("    { %s },  /* %s */" % (body, name))
    lines += ["};", "", "#endif /* HUDOS_SUN8X16_H */", ""]
    with open(path, "w") as f:
        f.write("\n".join(lines))

# ----------------------------------------------------------------- CJK ----

def render_glyph(ch, tmpdir):
    """ffmpeg-render one character; returns 128x128 list of 0/1 rows."""
    tf = os.path.join(tmpdir, "ch.txt")
    raw = os.path.join(tmpdir, "ch.raw")
    with open(tf, "wb") as f:
        f.write(chr(ch).encode("utf-8"))  # no newline: exact advance
    vf = ("drawtext=fontfile='%s':textfile='%s':fontsize=%d:"
          "fontcolor=white:x=%d:y=%d" % (CJK_FONT, tf, FS, PEN, PEN))
    subprocess.run(
        ["ffmpeg", "-hide_banner", "-loglevel", "error", "-y",
         "-f", "lavfi", "-i", "color=c=black:s=%dx%d:d=1" % (CANVAS, CANVAS),
         "-vf", vf, "-frames:v", "1", "-pix_fmt", "gray",
         "-f", "rawvideo", raw],
        check=True)
    data = open(raw, "rb").read()
    assert len(data) == CANVAS * CANVAS, len(data)
    return [[1 if data[y * CANVAS + x] >= 96 else 0 for x in range(CANVAS)]
            for y in range(CANVAS)]

def generate_cjk(chars, path, tmpdir):
    print("rendering %d CJK glyphs..." % len(chars))
    bitmaps = {ch: render_glyph(ch, tmpdir) for ch in chars}

    # union ink box over all glyphs == the box every glyph shares
    x0, y0, x1, y1 = CANVAS, CANVAS, 0, 0
    for bm in bitmaps.values():
        for y, row in enumerate(bm):
            if any(row):
                x = row.index(1)
                xe = len(row) - 1 - row[::-1].index(1)
                x0, x1 = min(x0, x), max(x1, xe)
                y0, y1 = min(y0, y), max(y1, y)
                break
        for y in range(CANVAS - 1, -1, -1):
            if any(bm[y]):
                y1 = max(y1, y)
                break
    w, h = x1 - x0 + 1, y1 - y0 + 1
    # contain-fit the union box into the cell with a 1px margin
    s = min((CELL - 2) / w, (CELL - 2) / h)
    dw, dh = w * s, h * s
    dx0, dy0 = (CELL - dw) / 2.0, (CELL - dh) / 2.0
    print("union box %dx%d -> cell scale %.3f" % (w, h, s))

    def downsample(bm):
        cell = []
        for ty in range(CELL):
            sy0 = y0 + (ty - dy0) / s
            sy1 = y0 + (ty + 1 - dy0) / s
            bits = 0
            for tx in range(CELL):
                sx0 = x0 + (tx - dx0) / s
                sx1 = x0 + (tx + 1 - dx0) / s
                ix0, ix1 = int(sx0), max(int(sx0) + 1, int(sx1 + 0.9999))
                iy0, iy1 = int(sy0), max(int(sy0) + 1, int(sy1 + 0.9999))
                hit = 0
                tot = 0
                for yy in range(max(0, iy0), min(CANVAS, iy1)):
                    for xx in range(max(0, ix0), min(CANVAS, ix1)):
                        tot += 1
                        hit += bm[yy][xx]
                if tot and hit * 2 >= tot:
                    bits |= 0x80000000 >> tx
            cell.append(bits)
        return cell

    chars = sorted(chars)
    lines = [
        "/* CJK 32x32 bitmap font: %d glyphs, codepoints sorted ascending." % len(chars),
        " * Auto-generated by gen_fonts.py (WenQuanYi Micro Hei, rendered via",
        " * ffmpeg drawtext). CJK_GLYPH: 32 rows x 32 bits per glyph,",
        " * bit 0x80000000 = leftmost pixel (see kcon_draw_cell()). */",
        "#ifndef HUDOS_CJK16X16_H",
        "#define HUDOS_CJK16X16_H",
        "",
        "#define CJK_N %d" % len(chars),
        "",
        "static const unsigned CJK_CODEP[CJK_N] = {",
    ]
    for i in range(0, len(chars), 8):
        lines.append("    " + " ".join("0x%05X," % c for c in chars[i:i + 8]))
    lines += ["};", "", "static const unsigned CJK_GLYPH[CJK_N * 32] = {"]
    for ch in chars:
        cell = downsample(bitmaps[ch])
        lines.append("    /* U+%04X %s */" % (ch, chr(ch)))
        for i in range(0, 32, 4):
            lines.append("    " + " ".join("0x%08XU," % v for v in cell[i:i + 4]))
    lines += ["};", "", "#endif /* HUDOS_CJK16X16_H */", ""]
    with open(path, "w") as f:
        f.write("\n".join(lines))
    print("wrote", path)

# ---------------------------------------------------------------- main ----

def main():
    srcs = sys.argv[1:] or [os.path.join(HERE, "..", "hudos_server.c")]
    chars = set()
    for s in srcs:
        with open(s, encoding="utf-8", errors="replace") as f:
            chars.update(ord(c) for c in f.read() if ord(c) > 0x7F)

    ascii_font = load_pcf(PCF)
    emit_sun8x16(ascii_font, os.path.join(HERE, "sun8x16.h"))
    print("wrote sun8x16.h (%d PCF glyphs)" % len(ascii_font))

    with tempfile.TemporaryDirectory() as tmpdir:
        generate_cjk(sorted(chars), os.path.join(HERE, "cjk16x16.h"), tmpdir)

if __name__ == "__main__":
    main()
