import { createEnvFile } from '../../utils/installer'

export default defineEventHandler(async (event) => {
  const body = await readBody(event)
  const crypto = await import('crypto')
  const fs = await import('fs')
  const path_mod = await import('path')

  const envPath = path_mod.default.resolve(process.cwd(), '.env')
  if (fs.existsSync(envPath)) {
    return { success: true, message: 'env already exists' }
  }

  const env = `# Cocokalo - Generated by setup wizard
DATABASE_URL="postgresql://${body.dbUser || 'postgres'}:${body.dbPassword || '123'}@${body.dbHost || 'localhost'}:${body.dbPort || '5432'}/${body.dbName || 'cocokalo'}"
REDIS_URL="${body.redisUrl || 'redis://localhost:6379'}"
PG_HOST="${body.dbHost || 'localhost'}"
PG_PORT="${body.dbPort || '5432'}"
PG_USER="${body.dbUser || 'postgres'}"
PG_PASSWORD="${body.dbPassword || '123'}"
PG_DB="${body.dbName || 'cocokalo'}"
JWT_SECRET="${crypto.randomBytes(32).toString('hex')}"
SITE_URL="${body.siteUrl || 'http://localhost:3000'}"
SITE_NAME="${body.siteName || 'Cocokalo'}"
NODE_ENV="development"
`

  fs.writeFileSync(envPath, env, 'utf-8')
  return { success: true, message: '环境配置已创建' }
})
