import { createEnvFile, installDependencies, runPrismaGenerate, runDbMigrate } from '../../utils/installer'

export default defineEventHandler(async (event) => {
  const body = await readBody(event)

  try {
    // Create .env if not exists
    if (!body.skipEnv) {
      const fs = await import('fs')
      const path_mod = await import('path')
      const envPath = path_mod.default.resolve(process.cwd(), '.env')
      if (!fs.existsSync(envPath)) {
        const envContent = `# Cocokalo - Generated by setup wizard
DATABASE_URL="postgresql://${body.dbUser || 'postgres'}:${body.dbPassword || '123'}@${body.dbHost || 'localhost'}:${body.dbPort || '5432'}/${body.dbName || 'cocokalo'}"
REDIS_URL="${body.redisUrl || 'redis://localhost:6379'}"
PG_HOST="${body.dbHost || 'localhost'}"
PG_PORT="${body.dbPort || '5432'}"
PG_USER="${body.dbUser || 'postgres'}"
PG_PASSWORD="${body.dbPassword || '123'}"
PG_DB="${body.dbName || 'cocokalo'}"
JWT_SECRET="${body.jwtSecret || require('crypto').randomBytes(32).toString('hex')}"
SITE_URL="${body.siteUrl || 'http://localhost:3000'}"
NODE_ENV="development"
SETUP_COMPLETED="true"
`
        fs.writeFileSync(envPath, envContent, 'utf-8')
      }
    }

    // Install dependencies
    if (!body.skipDeps) {
      await installDependencies()
    }

    // Generate Prisma and migrate
    if (!body.skipDb) {
      await runPrismaGenerate()
      await runDbMigrate()
    }

    // Create admin user if body says so
    if (body.createAdmin) {
      const { queryPg } = await import('../../utils/pg')
      const bcrypt = await import('bcryptjs')
      const adminExists = await queryPg('SELECT id FROM users WHERE username = $1', ['admin'])
      if (!adminExists.rows.length) {
        const { uniqueSlug } = await import('../../utils/pg')
        const adminSlug = await uniqueSlug('users')
        const salt = await bcrypt.genSalt(10)
        const hash = await bcrypt.hash(body.adminPassword || 'admin123', salt)
        await queryPg(
          'INSERT INTO users (slug, username, password, role) VALUES ($1, $2, $3, $4)',
          [adminSlug, 'admin', hash, 'admin']
        )
      }
    }

    return { success: true, message: '安装完成' }
  } catch (e: any) {
    throw createError({ statusCode: 500, message: `安装失败: ${e.message}` })
  }
})
